spring:
  application:
    name: dubbo-client
dubbo:
  application:
    name: dubbo-client
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.wzl.study.springboot.dubboclient.controller
server:
  port: 8081
