spring:
  application:
    name: dubbo-server
server:
  port: 8080

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 28080
  scan:
    base-packages: com.wzl.study.springboot.dubboserver.service
  application:
    name: dubbo-server